"""Product seed data, mirrored from yfic frontend src/data/products.ts."""


def _u(image_id: str, w: int = 1000) -> str:
    return f"https://images.unsplash.com/{image_id}?auto=format&fit=crop&w={w}&q=80"


PRODUCTS = [
    dict(
        id="p01", slug="manteau-laine-ecru",
        name={"fr": "Manteau en laine Écru", "en": "Écru Wool Coat"},
        category="femme", price=320, compare_at=None, is_new=True, featured=True,
        colors=[{"name": {"fr": "Écru", "en": "Ecru"}, "hex": "#E7DFD0"},
                {"name": {"fr": "Encre", "en": "Ink"}, "hex": "#1d1b16"}],
        sizes=["XS", "S", "M", "L", "XL"],
        image=_u("photo-1539109136881-3be0616acf4b"), image2=_u("photo-1551232864-3f0890e580d9"),
        tone="#d8cdbd",
        description={"fr": "Un manteau long à la ligne nette, taillé dans une laine douce et structurée. La pièce d’hiver qui se porte sur tout.",
                     "en": "A long coat with a clean line, cut from a soft, structured wool. The winter piece that goes with everything."},
        materials={"fr": "80% laine vierge, 20% cachemire. Doublure en cupro. Nettoyage à sec.",
                   "en": "80% virgin wool, 20% cashmere. Cupro lining. Dry clean only."},
        order=1,
    ),
    dict(
        id="p02", slug="chemise-lin-sable",
        name={"fr": "Chemise en lin Sable", "en": "Sand Linen Shirt"},
        category="homme", price=110, compare_at=None, is_new=False, featured=True,
        colors=[{"name": {"fr": "Sable", "en": "Sand"}, "hex": "#d8c7ab"},
                {"name": {"fr": "Blanc cassé", "en": "Off-white"}, "hex": "#f1ece2"}],
        sizes=["S", "M", "L", "XL"],
        image=_u("photo-1596755094514-f87e34085b2c"), image2=_u("photo-1602810318383-e386cc2a3ccf"),
        tone="#d8c7ab",
        description={"fr": "Lin lavé à la main, col souple et tombé impeccable. La chemise des beaux jours, du matin au soir.",
                     "en": "Hand-washed linen, soft collar and impeccable drape. The warm-weather shirt, morning to night."},
        materials={"fr": "100% lin lavé. Lavage à 30°. Se bonifie avec le temps.",
                   "en": "100% washed linen. Machine wash 30°. Gets better with time."},
        order=2,
    ),
    dict(
        id="p03", slug="robe-longue-terre",
        name={"fr": "Robe longue Terre", "en": "Terre Maxi Dress"},
        category="femme", price=185, compare_at=None, is_new=True, featured=True,
        colors=[{"name": {"fr": "Argile", "en": "Clay"}, "hex": "#b07a53"},
                {"name": {"fr": "Noir", "en": "Black"}, "hex": "#16140f"}],
        sizes=["XS", "S", "M", "L"],
        image=_u("photo-1595777457583-95e059d581b8"), image2=_u("photo-1583496661160-fb5886a0aaaa"),
        tone="#b07a53",
        description={"fr": "Une robe fluide qui suit le mouvement, ceinturée à la taille. Élégance sans effort, du déjeuner au dîner.",
                     "en": "A flowing dress that follows movement, belted at the waist. Effortless elegance, lunch to dinner."},
        materials={"fr": "100% viscose de bambou. Lavage délicat à froid.",
                   "en": "100% bamboo viscose. Gentle cold wash."},
        order=3,
    ),
    dict(
        id="p04", slug="pull-cachemire-brume",
        name={"fr": "Pull cachemire Brume", "en": "Brume Cashmere Knit"},
        category="femme", price=240, compare_at=None, is_new=False, featured=True,
        colors=[{"name": {"fr": "Brume", "en": "Mist"}, "hex": "#cfcabf"},
                {"name": {"fr": "Camel", "en": "Camel"}, "hex": "#b89968"}],
        sizes=["XS", "S", "M", "L"],
        image=_u("photo-1576566588028-4147f3842f27"), image2=_u("photo-1610652492500-ded49ceeb378"),
        tone="#cfcabf",
        description={"fr": "Maille fine en cachemire, douce comme un nuage. Le geste de luxe au quotidien.",
                     "en": "Fine cashmere knit, soft as a cloud. The everyday touch of luxury."},
        materials={"fr": "100% cachemire grade A. Lavage à la main, séchage à plat.",
                   "en": "100% grade-A cashmere. Hand wash, dry flat."},
        order=4,
    ),
    dict(
        id="p05", slug="pantalon-tailleur-encre",
        name={"fr": "Pantalon tailleur Encre", "en": "Ink Tailored Trousers"},
        category="homme", price=150, compare_at=None, is_new=False, featured=False,
        colors=[{"name": {"fr": "Encre", "en": "Ink"}, "hex": "#16140f"},
                {"name": {"fr": "Gris pierre", "en": "Stone grey"}, "hex": "#7c786f"}],
        sizes=["S", "M", "L", "XL"],
        image=_u("photo-1473966968600-fa801b869a1a"), image2=_u("photo-1594938298603-c8148c4dae35"),
        tone="#3a352d",
        description={"fr": "Une coupe droite et nette, pinces marquées, tombé parfait. Du bureau au soir, sans changer.",
                     "en": "A clean straight cut, pressed pleats, perfect drape. Office to evening, no change needed."},
        materials={"fr": "68% laine, 30% polyester, 2% élasthanne. Nettoyage à sec.",
                   "en": "68% wool, 30% polyester, 2% elastane. Dry clean."},
        order=5,
    ),
    dict(
        id="p06", slug="trench-classique-mastic",
        name={"fr": "Trench classique Mastic", "en": "Mastic Classic Trench"},
        category="femme", price=295, compare_at=None, is_new=False, featured=True,
        colors=[{"name": {"fr": "Mastic", "en": "Putty"}, "hex": "#cbbda3"}],
        sizes=["XS", "S", "M", "L", "XL"],
        image=_u("photo-1591047139829-d91aecb6caea"), image2=_u("photo-1578932750294-f5075e85f44a"),
        tone="#cbbda3",
        description={"fr": "Le trench intemporel, revisité dans une gabardine de coton dense. Ceinture à nouer, col révélable.",
                     "en": "The timeless trench, reworked in a dense cotton gabardine. Tie belt, convertible collar."},
        materials={"fr": "100% coton gabardine déperlant. Nettoyage à sec.",
                   "en": "100% water-repellent cotton gabardine. Dry clean."},
        order=6,
    ),
    dict(
        id="p07", slug="tshirt-coton-blanc",
        name={"fr": "T-shirt coton Blanc", "en": "White Cotton Tee"},
        category="homme", price=55, compare_at=None, is_new=True, featured=False,
        colors=[{"name": {"fr": "Blanc", "en": "White"}, "hex": "#f6f3ee"},
                {"name": {"fr": "Noir", "en": "Black"}, "hex": "#16140f"},
                {"name": {"fr": "Argile", "en": "Clay"}, "hex": "#b07a53"}],
        sizes=["S", "M", "L", "XL"],
        image=_u("photo-1521572163474-6864f9cf17ab"), image2=_u("photo-1583743814966-8936f5b7be1a"),
        tone="#e8e0d4",
        description={"fr": "Le t-shirt parfait : coton épais, col qui tient, coupe droite. L’essentiel, sans compromis.",
                     "en": "The perfect tee: heavy cotton, a collar that holds, straight cut. The essential, no compromise."},
        materials={"fr": "100% coton bio peigné 220g. Lavage à 30°.",
                   "en": "100% combed organic cotton 220gsm. Wash at 30°."},
        order=7,
    ),
    dict(
        id="p08", slug="blazer-structure-noir",
        name={"fr": "Blazer structuré Noir", "en": "Black Structured Blazer"},
        category="femme", price=265, compare_at=None, is_new=False, featured=True,
        colors=[{"name": {"fr": "Noir", "en": "Black"}, "hex": "#16140f"}],
        sizes=["XS", "S", "M", "L"],
        image=_u("photo-1632149877166-f75d49000351"), image2=_u("photo-1591369822096-ffd140ec948f"),
        tone="#2a2620",
        description={"fr": "Épaules nettes, taille marquée, un seul bouton. Le blazer qui transforme une silhouette.",
                     "en": "Clean shoulders, marked waist, single button. The blazer that transforms a silhouette."},
        materials={"fr": "62% laine, 36% viscose, 2% élasthanne. Doublure satinée.",
                   "en": "62% wool, 36% viscose, 2% elastane. Satin lining."},
        order=8,
    ),
    dict(
        id="p09", slug="sac-cuir-cognac",
        name={"fr": "Sac en cuir Cognac", "en": "Cognac Leather Bag"},
        category="accessoires", price=210, compare_at=None, is_new=True, featured=True,
        colors=[{"name": {"fr": "Cognac", "en": "Cognac"}, "hex": "#9a5f33"},
                {"name": {"fr": "Noir", "en": "Black"}, "hex": "#16140f"}],
        sizes=["Unique"],
        image=_u("photo-1584917865442-de89df76afd3"), image2=_u("photo-1591561954557-26941169b49e"),
        tone="#9a5f33",
        description={"fr": "Un cabas en cuir pleine fleur, anses portées épaule, format du quotidien. La patine viendra avec vous.",
                     "en": "A full-grain leather tote, shoulder straps, everyday format. The patina will come with you."},
        materials={"fr": "Cuir de vachette pleine fleur, tannage végétal. Doublure coton.",
                   "en": "Full-grain cowhide, vegetable tanned. Cotton lining."},
        order=9,
    ),
    dict(
        id="p10", slug="echarpe-laine-camel",
        name={"fr": "Écharpe en laine Camel", "en": "Camel Wool Scarf"},
        category="accessoires", price=85, compare_at=None, is_new=False, featured=False,
        colors=[{"name": {"fr": "Camel", "en": "Camel"}, "hex": "#b89968"},
                {"name": {"fr": "Gris", "en": "Grey"}, "hex": "#8a8276"}],
        sizes=["Unique"],
        image=_u("photo-1601924994987-69e26d50dc26"), image2=_u("photo-1457545195570-67f207084966"),
        tone="#b89968",
        description={"fr": "Une écharpe généreuse en laine brossée, chaude et légère. Le geste qui réchauffe une tenue.",
                     "en": "A generous brushed-wool scarf, warm and light. The touch that warms an outfit."},
        materials={"fr": "100% laine d’agneau brossée. Lavage à sec.",
                   "en": "100% brushed lambswool. Dry clean."},
        order=10,
    ),
    dict(
        id="p11", slug="jean-droit-indigo",
        name={"fr": "Jean droit Indigo", "en": "Indigo Straight Jeans"},
        category="homme", price=120, compare_at=None, is_new=False, featured=False,
        colors=[{"name": {"fr": "Indigo", "en": "Indigo"}, "hex": "#37415b"},
                {"name": {"fr": "Noir délavé", "en": "Washed black"}, "hex": "#2b2b2b"}],
        sizes=["S", "M", "L", "XL"],
        image=_u("photo-1542272604-787c3835535d"), image2=_u("photo-1604176354204-9268737828e4"),
        tone="#37415b",
        description={"fr": "Un denim brut japonais, coupe droite et franche. Il se patine avec le temps, à votre image.",
                     "en": "A Japanese raw denim, clean straight cut. It patinas over time, in your image."},
        materials={"fr": "100% coton denim 13oz. Premier lavage à froid recommandé.",
                   "en": "100% denim cotton 13oz. First cold wash recommended."},
        order=11,
    ),
    dict(
        id="p12", slug="jupe-plissee-ivoire",
        name={"fr": "Jupe plissée Ivoire", "en": "Ivory Pleated Skirt"},
        category="femme", price=130, compare_at=None, is_new=True, featured=False,
        colors=[{"name": {"fr": "Ivoire", "en": "Ivory"}, "hex": "#efe9dd"},
                {"name": {"fr": "Olive", "en": "Olive"}, "hex": "#5a5a43"}],
        sizes=["XS", "S", "M", "L"],
        image=_u("photo-1583846783214-7229a91b20ed"), image2=_u("photo-1594633312681-425c7b97ccd1"),
        tone="#efe9dd",
        description={"fr": "Plissé soleil qui prend la lumière et le mouvement. Une pièce romantique, jamais sage.",
                     "en": "Sunray pleats that catch light and movement. A romantic piece, never demure."},
        materials={"fr": "100% polyester recyclé plissé permanent. Lavage délicat.",
                   "en": "100% recycled polyester, permanent pleat. Delicate wash."},
        order=12,
    ),
    dict(
        id="p13", slug="casquette-coton-ecru",
        name={"fr": "Casquette coton Écru", "en": "Ecru Cotton Cap"},
        category="accessoires", price=45, compare_at=None, is_new=False, featured=False,
        colors=[{"name": {"fr": "Écru", "en": "Ecru"}, "hex": "#e7dfd0"},
                {"name": {"fr": "Encre", "en": "Ink"}, "hex": "#16140f"}],
        sizes=["Unique"],
        image=_u("photo-1588850561407-ed78c282e89b"), image2=_u("photo-1521369909029-2afed882baee"),
        tone="#e7dfd0",
        description={"fr": "Une casquette en sergé de coton lavé, visière souple, attache laiton. Le détail qui signe une allure.",
                     "en": "A washed cotton-twill cap, soft visor, brass buckle. The detail that signs a look."},
        materials={"fr": "100% coton sergé lavé. Attache laiton massif.",
                   "en": "100% washed cotton twill. Solid brass buckle."},
        order=13,
    ),
    dict(
        id="p14", slug="veste-surchemise-olive",
        name={"fr": "Surchemise Olive", "en": "Olive Overshirt"},
        category="homme", price=160, compare_at=None, is_new=True, featured=True,
        colors=[{"name": {"fr": "Olive", "en": "Olive"}, "hex": "#5a5a43"},
                {"name": {"fr": "Sable", "en": "Sand"}, "hex": "#cbbda3"}],
        sizes=["S", "M", "L", "XL"],
        image=_u("photo-1620012253295-c15cc3e65df4"), image2=_u("photo-1618354691373-d851c5c3a990"),
        tone="#5a5a43",
        description={"fr": "À mi-chemin entre la chemise et la veste. Coton lavé épais, poches plaquées, à porter ouverte.",
                     "en": "Halfway between shirt and jacket. Thick washed cotton, patch pockets, worn open."},
        materials={"fr": "100% coton lavé 8oz. Lavage à 30°.",
                   "en": "100% washed cotton 8oz. Wash at 30°."},
        order=14,
    ),
    dict(
        id="p15", slug="robe-chemise-rayee",
        name={"fr": "Robe-chemise Rayée", "en": "Striped Shirt Dress"},
        category="femme", price=145, compare_at=None, is_new=False, featured=False,
        colors=[{"name": {"fr": "Rayé bleu", "en": "Blue stripe"}, "hex": "#5b6b86"},
                {"name": {"fr": "Rayé terre", "en": "Earth stripe"}, "hex": "#9a6b4c"}],
        sizes=["XS", "S", "M", "L"],
        image=_u("photo-1612336307429-8a898d10e223"), image2=_u("photo-1566174053879-31528523f8ae"),
        tone="#5b6b86",
        description={"fr": "Une robe-chemise ceinturée, fraîche et facile. Le vestiaire d’été qui ne se prend pas au sérieux.",
                     "en": "A belted shirt dress, fresh and easy. The summer wardrobe that doesn’t take itself seriously."},
        materials={"fr": "100% coton popeline. Lavage à 30°.",
                   "en": "100% cotton poplin. Wash at 30°."},
        order=15,
    ),
    dict(
        id="p16", slug="ceinture-cuir-noir",
        name={"fr": "Ceinture en cuir Noir", "en": "Black Leather Belt"},
        category="accessoires", price=70, compare_at=None, is_new=False, featured=False,
        colors=[{"name": {"fr": "Noir", "en": "Black"}, "hex": "#16140f"},
                {"name": {"fr": "Cognac", "en": "Cognac"}, "hex": "#9a5f33"}],
        sizes=["S", "M", "L"],
        image=_u("photo-1624222247344-550fb60583dc"), image2=_u("photo-1553062407-98eeb64c6a62"),
        tone="#2a2620",
        description={"fr": "Cuir pleine fleur, boucle laiton patiné, surpiqûres discrètes. Une pièce qui traverse les années.",
                     "en": "Full-grain leather, aged brass buckle, discreet stitching. A piece that lasts for years."},
        materials={"fr": "Cuir pleine fleur tannage végétal. Boucle laiton.",
                   "en": "Full-grain vegetable-tanned leather. Brass buckle."},
        order=16,
    ),
]
